# Generated by Django 6.0.1 on 2026-01-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDB',
            fields=[
                ('Customerid', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('DoB', models.DateField()),
                ('Mobile_no', models.IntegerField()),
            ],
        ),
    ]
